version: "3"

services:

  www:
    build:
      context: conf/www
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: "www"
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ${PATH_WWW}:/var/www/html
      - ./conf/www/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - mysql

  mysql:
    build:
      context: conf/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}