version: "3"

services:

  www:
    build:
      context: conf/www
    container_name: 'www'
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql

  mysql:
    build:
      context: conf/mysql
    container_name: 'mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test